<?php
require ("conf.php");
$rtv_sala = mysqli_fetch_array(mysqli_query($conexao,"SELECT tv_sala FROM comandos where tv_sala"),MYSQLI_NUM);
$rluz_sala = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_sala FROM comandos where luz_sala"),MYSQLI_NUM);
$rsom_sala = mysqli_fetch_array(mysqli_query($conexao,"SELECT som_sala FROM comandos where som_sala"),MYSQLI_NUM);
$rar_sala = mysqli_fetch_array(mysqli_query($conexao,"SELECT ar_sala FROM comandos where ar_sala"),MYSQLI_NUM);
$rgeladeira_co = mysqli_fetch_array(mysqli_query($conexao,"SELECT geladeira_co FROM comandos where geladeira_co"),MYSQLI_NUM);
$rluz_co = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_co FROM comandos where luz_co"),MYSQLI_NUM);
$rtorneira_co = mysqli_fetch_array(mysqli_query($conexao,"SELECT torneira_co FROM comandos where torneira_co"),MYSQLI_NUM);
$rluz_la = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_la FROM comandos where luz_la"),MYSQLI_NUM);
$rmaq_la = mysqli_fetch_array(mysqli_query($conexao,"SELECT maq_la FROM comandos where maq_la"),MYSQLI_NUM);
$rluz_ga = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_ga FROM comandos where luz_ga"),MYSQLI_NUM);
$rluz_fu = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_fu FROM comandos where luz_fu"),MYSQLI_NUM);
$rluz_fr = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_fr FROM comandos where luz_fr"),MYSQLI_NUM);
$rtv_ca = mysqli_fetch_array(mysqli_query($conexao,"SELECT tv_ca FROM comandos where tv_ca"),MYSQLI_NUM);
$rluz_ca = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_ca FROM comandos where luz_ca"),MYSQLI_NUM);
$rluz_s1 = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_s1 FROM comandos where luz_s1"),MYSQLI_NUM);
$rluz_s2 = mysqli_fetch_array(mysqli_query($conexao,"SELECT luz_s2 FROM comandos where luz_s2"),MYSQLI_NUM);
$rar_ca = mysqli_fetch_array(mysqli_query($conexao,"SELECT ar_ca FROM comandos where ar_ca"),MYSQLI_NUM);
$rar_s1 = mysqli_fetch_array(mysqli_query($conexao,"SELECT ar_s1 FROM comandos where ar_s1"),MYSQLI_NUM);
$rar_s2 = mysqli_fetch_array(mysqli_query($conexao,"SELECT ar_s2 FROM comandos where ar_s2"),MYSQLI_NUM);
// Destinada A Criação de Variaveis para se ver no navegador
if($rtv_sala != 0){
    $tv_sala = "ON";
} else $tv_sala = "OFF";
if($rluz_sala != 0){
    $luz_sala = "ON";
} else $luz_sala = "OFF";
if($rsom_sala != 0){
    $som_sala = "ON";
} else $som_sala = "OFF";
if($rar_sala != 0){
    $ar_sala = "ON";
} else $ar_sala = "OFF";
if($rgeladeira_co != 0){
    $geladeira_co = "ON";
} else $geladeira_co = "OFF";
if($rtorneira_co != 0){
    $torneira_co = "ON";
} else $torneira_co = "OFF";
if($rluz_co != 0){
    $luz_co = "ON";
} else $luz_co = "OFF";
if($rmaq_la != 0){
    $maq_la = "ON";
} else $maq_la = "OFF";
if($rluz_la != 0){
    $luz_la = "ON";
} else $luz_la = "OFF";
if($rluz_ga != 0){
    $luz_ga = "ON";
} else $luz_ga = "OFF";
if($rluz_fu != 0){
    $luz_fu = "ON";
} else $luz_fu = "OFF";
if($rluz_fr != 0){
    $luz_fr = "ON";
} else $luz_fr = "OFF";
if($rtv_ca != 0){
    $tv_ca = "ON";
} else $tv_ca = "OFF";
if($rluz_ca != 0){
    $luz_ca = "ON";
} else $luz_ca = "OFF";
if($rluz_s1 != 0){
    $luz_s1 = "ON";
} else $luz_s1 = "OFF";
if($rluz_s2 != 0){
    $luz_s2 = "ON";
} else $luz_s2 = "OFF";
if($rar_ca != 0){
    $ar_ca = "ON";
} else $ar_ca = "OFF";
if($rar_s1 != 0){
    $ar_s1 = "ON";
} else $ar_s1 = "OFF";
if($rar_s2 != 0){
    $ar_s2 = "ON";
} else $ar_s2 = "OFF";